version: "3.9"

services:
  db:
    image: postgres:15
    container_name: meu-bolso-db
    environment:
      POSTGRES_DB: meu-bolso-db
      POSTGRES_USER: rafasdoliveira
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - meu-bolso-net

  api:
    image: meu-bolso-api:v1.0.0
    container_name: meu-bolso-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - meu-bolso-net

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - meu-bolso-net

  jenkins:
    image: jenkins-custom
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - meu-bolso-net
    depends_on:
      - sonarqube

networks:
  meu-bolso-net:
    driver: bridge

volumes:
  pgdata:
  jenkins_home:
