services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--httpPort=9090
    ports: 
      - '9090:9090'
      - '50010:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home: 