services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--httpPort=9090
    ports: 
      - '9090:9090'
      - '50010:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  sonarqube:
    image: sonarqube:9.9.8-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - ./sonar/data:/opt/sonarqube/data
      - ./sonar/extensions:/opt/sonarqube/extensions
      - ./sonar/logs:/opt/sonarqube/logs

volumes:
  jenkins_home:
  sonar_data:
  sonar_extensions:
  sonar_logs: